config/routes.rb
Rails.application.routes.draw do
  
  
  resources :tags
  resources :topics do 
    resources :posts do 
      resources :comments
      end
  end
  # get 'home/index'
  root 'home#index'
  resources :allposts
  # get '/allposts', to 'allposts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts, dependent: :destroy


    validates :name, length: { minimum: 3 }
    validates :subtopic, presence: true
    
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:name, :subtopic, :link)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name,class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :subtopic %>
    <%= form.text_field :subtopic,class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link ,class:'form-control' %>
  </div>

  <div class="actions mt-4">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1> List Topics</h1>
<%= link_to 'Add New Topic', new_topic_path, class:'btn btn-primary' %>

<table class="table table-hover mt-3">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Subtopic</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.subtopic %></td>
        <td><%= topic.link %></td>
        <td><%= link_to 'Posts',topic_posts_path(topic.id) , class:'btn btn-primary'  %></td>
        <td><%= link_to 'Show', topic, class:'btn btn-info'  %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic),class:'btn btn-info'   %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-info'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<div class="card p-2 m-3" style="width: 18rem;">
<div class="card-header">

<p id="notice"><%= notice %></p>
</div>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Subtopic:</strong>
  <%= @topic.subtopic %>
</p>

<p>
  <strong>Link:</strong>
  <%= @topic.link %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic),class:'btn btn-primary' %> 
<%= link_to 'Back', topics_path,class:'btn btn-primary mt-3' %>
</div>