config/routes.rb
Rails.application.routes.draw do
  
  
  resources :tags
  resources :topics do 
    resources :posts do 
      resources :comments
      end
  end
  # get 'home/index'
  root 'home#index'
  resources :allposts
  # get '/allposts', to 'allposts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/allposts_controller.rb
class AllpostsController < ApplicationController
    Post_per_page = 5
    def index
        @page=params.fetch(:page,0).to_i
        @allposts =Post.offset(@page * Post_per_page).limit(Post_per_page)

    end

end

app/helpers/allposts_helper.rb
module AllpostsHelper
end

app/views/allposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1> List Topics</h1>
<%= link_to 'Add New Topic', new_topic_path, class:'btn btn-primary' %>

<table class="table table-hover mt-3">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @allposts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.desc %></td>
        <td><%= post.topic_id %></td>
        <td><%= link_to 'Show', topic_post_url(post.topic_id, post.id) %></td>
        <td><%= link_to 'Edit', edit_topic_post_url(post.topic_id, post.id) %></td>
        <td><%= link_to 'Destroy', topic_post_path(post.topic_id, post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<div class="txt-center">
<ul class="pagination">
<%= link_to " Previous Page ", allposts_path(page: @page - 1), class:"page-item btn border m-2" %>
<%= link_to @page  , allposts_path(page: @page), class:"page-item btn border m-2" %>
<%= link_to @page + 1  , allposts_path(page: @page + 1), class:"page-item btn border m-2" %>
<%= link_to @page + 2  , allposts_path(page: @page + 2), class:"page-item btn border m-2" %>
<%= link_to " Next Page ", allposts_path(page: @page + 1), class:"page-item btn border m-2" %>
</ul>
</div>

<br>