config/routes.rb
Rails.application.routes.draw do
  
  
  resources :tags
  resources :topics do 
    resources :posts do 
      resources :comments
      end
  end
  # get 'home/index'
  root 'home#index'
  resources :allposts
  # get '/allposts', to 'allposts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :topic
    has_many :comments, dependent: :destroy
    has_and_belongs_to_many :tags

    accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: :all_blank

    validates :name, :topic_id, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_topic 
  before_action :set_post, only: %i[ show edit update destroy ]
 

  # GET /posts or /posts.json
  def index
    @posts = Post.where("topic_id = ?", params[:topic_id])
    # @posts= topic.Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    
    @comments =Comment.where("post_id = ?", params[:id])
    @post = Post.find(params[:id])
    @tags = @post.tags

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  def new
    puts @post
    @post = Post.new
    @tags=Tag.all
    
  end

  # GET /posts/1/edit
  def edit
    @tags=Tag.all
  end

  # POST /posts or /posts.json
  def create
    @post = Post.create(post_params)
    @post.topic_id=@topic.id
    
  
    respond_to do |format|
      if @post
        @tagname = params[:tag_name]
        p @tagname
        if  @tagnam.present?
          newTag = Tag.create(post_params_tags)
          @post.tags << newTag
        end
     
       

        format.html { redirect_to topic_posts_url(@post.topic_id), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to  topic_posts_url(@post.topic_id), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url(@post.topic_id), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic=Topic.find(params[:topic_id])
    end

    def set_post
      
      @post = @topic.posts.find(params[:id])

    end
    

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :desc, :topic_id, :tag_name, tag_ids:[])
    end
    # def post_params_tags
    #   params.require(:post).permit(:tag_name)
    # end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@topic, @post] do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this @post from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <% @tags.each do |tag| %>
    <div>
     <%= check_box_tag "post[tag_ids][]", tag.id, @post.tags.include?(tag) %> 
     <%= tag.tag_name %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Tags %>
    <%= form.text_field :tag_name %>
  </div>

  <div class="field">
    <%= form.label :topic_id,class:"invisible" %>
    <%= form.text_field :topic_id, id:"disabledTextInput" ,value:@topic.id,  class:"invisible" %>
  </div>

  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', topic_posts_path(@topic) %> |
<%= link_to 'Back',topic_posts_path(@topic) %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<%= link_to 'Create New Post', new_topic_post_path(@topic), class:'btn btn-primary' %>
  
    <% @posts.each do |post| %>
     <div class="card p-3 my-2 shadow"> 
     <p>
     <strong>Name:</strong>
        <%= post.name %>
     </p>
     <p>
     <strong>Description:</strong>
       <%= post.desc %>
     </p>
      <p>
      <strong>Topic :</strong>
       <%= post.topic_id %>
      </p> 
      <p>
      <div>
       <%= link_to 'Show', topic_post_url(@topic, post.id), class:'btn btn-primary'%>
       <%= link_to 'Edit', edit_topic_post_url(@topic, post.id), class:'btn btn-primary' %>
       <%= link_to 'Destroy', topic_post_path(@topic, post.id), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-primary' %>
      </div>
      </div>
    <% end %>
 

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', topic_posts_path(@topic) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card p-3 shadow">
<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @post.desc %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @post.topic_id %>
</p>
<p><strong>Tags: </strong></p>
<% @tags.each do |tag| %>
<p>
<%= tag.tag_name %>
</p>
<% end %>
<div>
<%= link_to 'Edit', edit_topic_post_url(@topic, @post), class:'btn btn-info' %> |
<%= link_to 'Back', topic_posts_path(@topic), class:'btn btn-primary' %>
</div>
</div>
<br/><br/>

<h1>Comments</h1><br/>
<%= link_to 'Add new Comment', new_topic_post_comment_url(@topic, @post, @comment), class:'btn btn-primary' %> 
<br/><br/>

<% @comments.each do |comment| %>
  <p><%= comment.comment %></p>
  
  <% end %>